name: Prettier

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'
      - name: Run Prettier
        run: |
          npm ci
          npm run format
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Apply Prettier Changes